### ISSUE TITLE
Slides are offset when transition to full screen and back

### ISSUE THREAD

**Issue by mike-ward** [krasimir/simpre#1]
View a slide in normal window. Go full screen. Then restore. Slide is shifted.

![image](https://user-images.githubusercontent.com/567927/157326556-e8f8dffb-65bb-49dc-b204-67f27633e187.png)

**Comment by krasimir** [comment]
Good catch ... I know about this issue but decided to leave it for a later fix. Even if it happens while I'm presenting I'll simply hit refresh and will solve the problem. The fix that I can do will probably cost more in filesize and performance.

**Comment by mike-ward** [comment]
Your call. F5 works for me.
